notifications:
  email: false

language: cpp

os: linux
dist: bionic

jobs:
  include:
    - name: "STM32"
      dist: focal
      env:
        - TOOLCHAIN=../32blit-beta/32blit.toolchain
        - RELEASE_FILE=${TRAVIS_BUILD_DIR}${REPO}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}-STM32
      addons:
        apt:
          gcc-arm-none-eabi
          libnewlib-arm-none-eabi
          libstdc++-arm-none-eabi-newlib
          python3-pip
          python3-setuptools
          zip
      before_deploy:
        - make install
        - tar -zcf ${RELEASE_FILE}.tar.gz bin/
        - zip -9 ${RELEASE_FILE}.zip bin/*
      deploy:
        provider: releases
        file:
          - ${RELEASE_FILE}.tar.gz
          - ${RELEASE_FILE}.zip
        on:
          tags: true
        edge: true

install:
  - git clone --depth 1 https://github.com/pimoroni/32blit-beta
  - python3 -m pip install 32blit

script:
  - mkdir build && cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN -DCMAKE_INSTALL_PREFIX=`pwd` -D32BLIT_PATH=../32blit-beta $CMAKE_ARGS ..
  - cmake --build .